mqtt:
  enabled: false

record:
  enabled: true
  retain:
    days: 7
    mode: motion

cameras:
  living_room:
    ffmpeg:
      inputs:
        - path: rtsp://tapoC120:password@192.168.3.69:554/stream1
          roles:
            - detect
            - record
    motion:
      enabled: true
      mask:

        - 0.357,0.046,0.357,0,0,0,0.002,0.048
        - 0.755,0.094,0.739,0.209,0.842,0.311,0.864,0.174
detect:
  enabled: false

version: 0.16-0

