include:
  - path: dispatcharr/docker-compose.yml
  - path: mariadb/docker-compose.yml
  - path: booklore/docker-compose.yml
  - path: caddy/docker-compose.yml
  - path: frigate/docker-compose.yml
  - path: game-thumbs/docker-compose.yml
  - path: teamarr/docker-compose.yml
  - path: glance/docker-compose.yml
  - path: chaptarr/docker-compose.yml
  - path: plex/docker-compose.yml
  - path: jellyseerr/docker-compose.yml
  - path: maintainerr/docker-compose.yml
  - path: radarr/docker-compose.yml
  - path: sonarr/docker-compose.yml
  - path: prowlarr/docker-compose.yml
  - path: huntarr/docker-compose.yml
  - path: qbittorrent/docker-compose.yml
  - path: unpackerr/docker-compose.yml
  - path: bazarr/docker-compose.yml
  - path: gluetun/docker-compose.yml
  - path: cloudflare-ddns/docker-compose.yml
  - path: profilarr/docker-compose.yml
  - path: qui/docker-compose.yml
